[package]
name = "pycrdt"
version = "0.12.26"
edition = "2021"

[lib]
name = "pycrdt"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.140"
yrs = "0.24.0"

[dependencies.pyo3]
version = "0.25.1"
